[project]
name = "mcp-server-actual"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mcp[cli]>=1.21.0",
]

[tool.uv.workspace]
members = [
    "erp_mcp",
]
